# Generated by Django 2.2.6 on 2020-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buyer_phone',
            field=models.CharField(max_length=20),
        ),
    ]
